// reactJS/basic-todo/src/App.js
import "./App.css";
import { useEffect, useRef, useState } from "react";
function App() {
  const [todos, setTodos] = useState([]);
  // Binding
  const todoText = useRef();

  // Side Effects Lifestyle

  useEffect(() => {
    const existingTodos = localStorage.getItem("todos");
    setTodos(existingTodos ? JSON.parse(existingTodos) : []);
  }, []);
  function addTodo(event) {
    event.preventDefault();
    const next = [...todos, todoText.current.value];
    setTodos(next);
    localStorage.setItem("todos", JSON.stringify(next));
  }
  return (
    <div>
      <ul>
        {todos.map((todo) => (
          <li key={todo}>{todo}</li>
        ))}
      </ul>
      <form onSubmit={addTodo}>
        <input ref={todoText} />
        <input type="submit" value="Submit" />
      </form>
    </div>
  );
}

export default App;

// angular/basic-todo/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  //  State
  // Defining a string array and setting it to empty.
  todos: string[] = [];
  todoText = '';

  // Called when component is first init
  ngOnInit() {
    // Grab from localstorage
    const existingTodos = localStorage.getItem('todos');

    this.todos = JSON.parse(existingTodos as string) || [];
  }
  addTodo() {
    this.todos.push(this.todoText);
    localStorage.setItem('todos', JSON.stringify(this.todos));
  }
}

<ul>
  <li *ngFor="let todo of todos">{{ todo }}</li>
</ul>
<form (ngSubmit)="addTodo()">
  <input name="todotext" [(ngModel)]="todoText" />
  <input type="submit" value="Add Todo" />
</form>
